files:
  - source: /app/src/main/res/values/string*.xml
    ignore:
      - /app/src/main/res/values/strings_keys.xml
    translation: /app/src/main/res/values-%two_letters_code%/%original_file_name%
