name: swassistant
description: Character sheet and dice app for the FFG Star Wars tabletop RPG

publish_to: 'none'

version: 3.0.0+2000000

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # Add this line
    sdk: flutter

  intl: ^0.17.0
  firebase_core: ^1.8.0
  firebase_crashlytics: "^2.2.4"
  shared_preferences: ^2.0.8
  path_provider: ^2.0.5
  cupertino_icons: ^1.0.3
  url_launcher: ^6.0.12
  permission_handler: ^8.2.5
  file_picker: ^4.1.6
  flutter_speed_dial: ^4.6.0
  in_app_purchase: ^1.0.9
  googleapis: ^6.0.0
  google_sign_in: ^5.2.0
  extension_google_sign_in_as_googleapis_auth: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  generate: true

  uses-material-design: true

  assets:
    - assets/testing/
    - assets/
