name: swassistant
description: Character sheet and dice app for the FFG Star Wars TTRPG

publish_to: 'none'

version: 4.0.6+167

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl: ^0.17.0
  firebase_core: ^2.4.1
  firebase_crashlytics: ^3.0.10
  shared_preferences: ^2.0.16
  path_provider: ^2.0.11
  cupertino_icons: ^1.0.5
  url_launcher: ^6.1.7
  file_picker: ^5.2.5
  in_app_purchase: ^3.1.1
  googleapis: ^10.0.0
  google_sign_in: ^5.4.3
  extension_google_sign_in_as_googleapis_auth: ^2.0.7
  device_info_plus: ^8.0.0
  package_info_plus: ^3.0.2
  universal_internet_checker: ^0.1.2
  uuid: ^3.0.7
  # flutter_speed_dial: ^5.0.0+1
  # dynamic_color: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  generate: true

  uses-material-design: true

  assets:
    - assets/
