name: swassistant
description: Character sheet and dice app for the FFG Star Wars TTRPG

publish_to: 'none'

version: 4.2.8+192

environment:
  sdk: ">=3.0.0-417.2.beta <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl: any
  shared_preferences: ^2.2.0
  path_provider: ^2.0.15
  cupertino_icons: ^1.0.5
  url_launcher: ^6.1.12
  file_picker: ^5.3.3
  in_app_purchase: ^3.1.7
  device_info_plus: ^9.0.2
  package_info_plus: ^4.0.2
  googleapis: ^11.3.0
  uuid: ^3.0.7
  flutter_dotenv: ^5.1.0
  darkstorm_common: ^1.0.6
  stupid: ^0.2.4
  flutter_secure_storage: ^8.0.0
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - .stupid
