name: swassistant
description: Character sheet and dice app for the FFG Star Wars tabletop RPG

publish_to: 'none'

version: 3.0.0+2000000

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^1.4.0
  firebase_crashlytics: "^2.1.1"
  shared_preferences: ^2.0.6
  path_provider: ^2.0.2
  cupertino_icons: ^1.0.3
  url_launcher: ^6.0.9
  permission_handler: ^8.1.4+2
  file_picker: ^4.0.0
  flutter_speed_dial: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/testing/
    - assets/

