name: swassistant
description: Character sheet and dice app for the FFG Star Wars TTRPG

publish_to: 'none'

version: 3.2.4+157

environment:
  sdk: ">=2.16.0-134.1.beta <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # Add this line
    sdk: flutter

  intl: ^0.17.0
  firebase_core: ^1.12.0
  firebase_crashlytics: ^2.5.1
  shared_preferences: ^2.0.13
  path_provider: ^2.0.9
  cupertino_icons: ^1.0.4
  url_launcher: ^6.0.20
  file_picker: ^4.4.0
  # flutter_speed_dial: ^5.0.0+1
  in_app_purchase: ^2.0.1
  googleapis: ^8.0.0
  google_sign_in: ^5.2.3
  extension_google_sign_in_as_googleapis_auth: ^2.0.4
  device_info_plus: ^3.2.2
  package_info_plus: ^1.3.1
  universal_internet_checker: ^0.1.2
  uuid: ^3.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

flutter:
  generate: true

  uses-material-design: true

  assets:
    - assets/
