name: swassistant
description: Character sheet and dice app for the FFG Star Wars TTRPG

publish_to: 'none'

version: 4.0.3+164

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl: ^0.17.0
  firebase_core: ^1.20.0
  firebase_crashlytics: ^2.8.6
  shared_preferences: ^2.0.15
  path_provider: ^2.0.11
  cupertino_icons: ^1.0.5
  url_launcher: ^6.1.5
  file_picker: ^4.6.1
  in_app_purchase: ^3.0.6
  googleapis: ^9.1.0
  google_sign_in: ^5.4.0
  extension_google_sign_in_as_googleapis_auth: ^2.0.6
  device_info_plus: ^3.2.4
  package_info_plus: ^1.4.2
  universal_internet_checker: ^0.1.2
  uuid: ^3.0.6
  # flutter_speed_dial: ^5.0.0+1
  # dynamic_color: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  generate: true

  uses-material-design: true

  assets:
    - assets/
