name: swassistant
description: Character sheet and dice app for the FFG Star Wars TTRPG

publish_to: 'none'

version: 4.3.0+195

environment:
  sdk: ">=3.0.0-417.2.beta <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl: any
  shared_preferences: ^2.2.2
  path_provider: ^2.1.2
  cupertino_icons: ^1.0.6
  url_launcher: ^6.2.5
  file_picker: ^6.1.1
  in_app_purchase: ^3.1.13
  device_info_plus: ^9.1.2
  package_info_plus: ^5.0.1
  googleapis: ^12.0.0
  uuid: ^4.3.3
  flutter_dotenv: ^5.1.0
  darkstorm_common: ^1.0.11
  stupid: ^0.2.6
  flutter_secure_storage: ^9.0.0
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - .stupid
