name: swassistant
description: Character sheet and dice app for the FFG Star Wars tabletop RPG

publish_to: 'none'

version: 3.0.0+136

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # Add this line
    sdk: flutter

  intl: ^0.17.0
  firebase_core: ^1.10.5
  firebase_crashlytics: "^2.4.3"
  shared_preferences: ^2.0.11
  path_provider: ^2.0.8
  cupertino_icons: ^1.0.4
  url_launcher: ^6.0.17
  permission_handler: ^8.3.0
  file_picker: ^4.2.7
  # flutter_speed_dial: ^5.0.0+1
  in_app_purchase: ^2.0.1
  googleapis: ^7.0.0
  google_sign_in: ^5.2.1
  extension_google_sign_in_as_googleapis_auth: ^2.0.4
  device_info_plus: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  generate: true

  uses-material-design: true

  assets:
    - assets/testing/
    - assets/
