name: swassistant
description: Character sheet and dice app for the FFG Star Wars tabletop RPG

publish_to: 'none'

version: 3.1.1+143

environment:
  sdk: ">=2.16.0-134.1.beta <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # Add this line
    sdk: flutter

  intl: ^0.17.0
  firebase_core: ^1.11.0
  firebase_crashlytics: "^2.4.5"
  shared_preferences: ^2.0.12
  path_provider: ^2.0.8
  cupertino_icons: ^1.0.4
  url_launcher: ^6.0.18
  permission_handler: ^8.3.0
  file_picker: ^4.3.2
  # flutter_speed_dial: ^5.0.0+1
  in_app_purchase: ^2.0.1
  googleapis: ^7.0.0
  google_sign_in: ^5.2.3
  extension_google_sign_in_as_googleapis_auth: ^2.0.4
  device_info_plus: ^3.2.1
  uuid: ^3.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

flutter:
  generate: true

  uses-material-design: true

  assets:
    - assets/testing/
    - assets/
